version: '3'

services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
     - "8080:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"